name: CI analysis of ginkgo

on: [push] process of ginkgo

jobs: chief engineer
  build:test for flavone

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |run_hw -f Makefile.fpga
        echo Add other actions to build,
        echo test, and deploy your project.
